apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  #DB_HOST: mysql # mysql component service name
  DB_HOST: db-dev.aadhyuar2105.online
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  # these labels are deployment related labels
  labels:
    componet: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      tier: app
      project: expense
  # pod definition
  template:
    metadata:
      labels:
        component: backend
        tier: app
        project: expense
    spec:
      initContainers:
      - name: init-myservice
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup mysql; do echo waiting for myservice; sleep 2; done"]
      containers:
      - name: backend
        image: joindevops/backend:v1.0
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            #filure throshold is 2, if container fails 2 times then it will restart the container,initial deley given 30s so it will not create pod in 30s
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 5
          initialDelaySeconds: 30
        envFrom:
        - configMapRef:
            name: backend
            
    
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    tier: app
    project: expense
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port