kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: expense
  # these labels are deployment related labels
  labels:
    componet: mysql
    project: expense
    tier: db
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      tier: db
      project: expense
  # pod definition
  template:
    metadata:
      labels:
        component: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0